metadata:
  type: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.Configuration.AvatarDisplayConfig
  assembly_file: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.dll
  for: component.score.avatar_display
  version: 1 # format version
data:
  images:
    - file: Contents/res/images/avatars/1.png
    - file: Contents/res/images/avatars/2.png
    - file: Contents/res/images/avatars/3.png
    - file: Contents/res/images/avatars/4.png
    - file: Contents/res/images/avatars/5.png
  # will try to create N circles, where N is the length of avatar image entries
  # empty or invalid (e.g. file missing) entries count, but they will not be drawn
  # use this feature to create "empty" avatars
  layout:
    x: 0.8% # x position (anchor: left)
    y: 6% # y position (anchor: top)
    width: 25.5%
    height: 8.5%
