metadata:
  type: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.Configuration.ScalingConfig
  assembly_file: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.dll
  for: component.score.scaling_responder
  version: 1 # format version
data:
  base: 960x540
  tap_point:
    start: 114x114
    end: 140x140
  tap_bar_chain: 4x4
  tap_bar_node: 16x16
  note:
    start: 60x60
    end: 120x120
  special_note:
    start: 200x200
    end: 280x280
  sync_line: 5x0
  # used for scaling ribbon width
  visual_note_small:
    start: 40x40
    end: 80x80
  visual_note_large:
    start: 50x50
    end: 100x100
  special_note_aura:
    start: 100x100
    end: 280x280
  special_note_socket: 280x280
  hit_rank: 180x45
  avatar_border: 3x0
  combo_aura: 240x120
  combo_text: 222x36
  combo_number: 48x48 # real image size, including blank edges
