metadata:
  type: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.Configuration.SfxControllerConfig
  assembly_file: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.dll
  for: component.score.sfx_controller
  version: 1 # format version
data:
  sfx_volume: 100% # volume of sound effects (0% - 100%)
  sfx: # sound effect files; format: 44100 Hz, 16-bit integer, 2 channels
    tap:
      perfect: Contents/res/sfx/rhy_tap.wav
      great: Contents/res/sfx/app_great.wav
      nice: Contents/res/sfx/app_good.wav
      bad: Contents/res/sfx/app_fast.wav
      miss: Contents/res/sfx/app_miss.wav
    hold:
      perfect: Contents/res/sfx/rhy_tap.wav
      great: Contents/res/sfx/app_great.wav
      nice: Contents/res/sfx/app_good.wav
      bad: Contents/res/sfx/app_fast.wav
      miss: Contents/res/sfx/app_miss.wav
    flick:
      perfect: Contents/res/sfx/app_flick.wav
      great: Contents/res/sfx/app_great.wav
      nice: Contents/res/sfx/app_good.wav
      bad: Contents/res/sfx/app_fast.wav
      miss: Contents/res/sfx/app_miss.wav
    slide:
      perfect: Contents/res/sfx/rhy_tap.wav
      great: Contents/res/sfx/app_great.wav
      nice: Contents/res/sfx/app_good.wav
      bad: Contents/res/sfx/app_fast.wav
      miss: Contents/res/sfx/app_miss.wav
    slide_hold: Contents/res/sfx/app_hold_up.wav
    hold_hold: Contents/res/sfx/app_hold.wav
    slide_end:
      perfect: Contents/res/sfx/app_hold_rub.wav
      great: Contents/res/sfx/app_great.wav
      nice: Contents/res/sfx/app_good.wav
      bad: Contents/res/sfx/app_fast.wav
      miss: Contents/res/sfx/app_miss.wav
    hold_end:
      perfect: Contents/res/sfx/app_hold_end.wav
      great: Contents/res/sfx/app_great.wav
      nice: Contents/res/sfx/app_good.wav
      bad: Contents/res/sfx/app_fast.wav
      miss: Contents/res/sfx/app_miss.wav
    special:
      perfect: Contents/res/sfx/app_special.wav
      great: Contents/res/sfx/app_great.wav
      nice: Contents/res/sfx/app_good.wav
      bad: Contents/res/sfx/app_fast.wav
      miss: Contents/res/sfx/app_miss.wav
    special_end: Contents/res/sfx/app_special_end.wav
    special_hold: Contents/res/sfx/app_special_loop.wav
    shouts: # around 3 seconds
      #- Contents/res/sfx/shout01.wav
      #- Contents/res/sfx/shout02.wav
      - Contents/res/sfx/shout03.wav
