metadata:
  type: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.Configuration.TapPointsConfig
  assembly_file: OpenMLTD.MilliSim.Extension.Components.ScoreComponents.dll
  for: component.score.tap_points
  version: 1 # format version
data:
  images:
    tap_point:
      file: Contents/res/images/ui/tap_point.png # 128x128
      blank_edge:
        left: 14
        top: 14
        right: 14
        bottom: 14
    tap_bar_chain:
      file: Contents/res/images/ui/tap_bar_chain.png # 32x32
    tap_bar_node:
      file: Contents/res/images/ui/tap_bar_node.png # 74x74
  layout:
    x: 50% # x position (anchor: center)
    y: 83% # y position (anchor: middle)
    width: 61% # width (from center of left-most point, to center of right-most point)
  opacity: 80%
