metadata:
  type: OpenMLTD.MilliSim.Extension.Components.CoreComponents.Configuration.FpsOverlayConfig
  assembly_file: OpenMLTD.MilliSim.Extension.Components.CoreComponents.dll
  for: component.core.fps_overlay
  version: 1 # format version
data:
  visible: yes
  font_size: 15
  text_fill: '#ffff'
